-- Шаблон UPDATE для rtc_balance, trigger<0 (сокращение):
-- ALTER TABLE heli_pandas UPDATE status_change = 3
-- WHERE status_id=2 AND status_change=0 AND group_by=1
-- ORDER BY ppr DESC, sne DESC, mfg_date ASC
-- LIMIT abs(:trigger_pr_final)
-- SETTINGS allow_experimental_alter_update = 1;

-- Шаблон UPDATE для rtc_balance, trigger>0 (дефицит):
-- Этап1: 5→2; Этап2: 3→2; Этап3: 1→2 (при (D-version_date) >= repair_time)
-- ALTER TABLE heli_pandas UPDATE status_change = 2 WHERE status_id=5 AND status_change=0 AND group_by=1;
-- ALTER TABLE heli_pandas UPDATE status_change = 2 WHERE status_id=3 AND status_change=0 AND group_by=1;
-- ALTER TABLE heli_pandas UPDATE status_change = 2 
-- WHERE status_id=1 AND status_change=0 AND group_by=1 AND dateDiff('day', version_date, (SELECT min(dates) FROM flight_program_fl)) >= (
--   SELECT coalesce(repair_time, 0) FROM md_components WHERE partno_comp = heli_pandas.partseqno_i
-- );

-- Шаблон UPDATE для rtc_balance, trigger<0 (сокращение):
-- ALTER TABLE heli_pandas UPDATE status_change = 3
-- WHERE status_id=2 AND status_change=0 AND group_by=2
-- ORDER BY ppr DESC, sne DESC, mfg_date ASC
-- LIMIT abs(:trigger_pr_final)
-- SETTINGS allow_experimental_alter_update = 1;

-- Шаблон UPDATE для rtc_balance, trigger>0 (дефицит):
-- Этап1: 5→2; Этап2: 3→2; Этап3: 1→2 (при (D-version_date) >= repair_time)
-- ALTER TABLE heli_pandas UPDATE status_change = 2 WHERE status_id=5 AND status_change=0 AND group_by=2;
-- ALTER TABLE heli_pandas UPDATE status_change = 2 WHERE status_id=3 AND status_change=0 AND group_by=2;
-- ALTER TABLE heli_pandas UPDATE status_change = 2 
-- WHERE status_id=1 AND status_change=0 AND group_by=2 AND dateDiff('day', version_date, (SELECT min(dates) FROM flight_program_fl)) >= (
--   SELECT coalesce(repair_time, 0) FROM md_components WHERE partno_comp = heli_pandas.partseqno_i
-- );
